listeners:
- query_port: 25577
  motd: '&bRede Minecraft &7- &fEstilo Hylex\n&eServidor em Manutencao'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: lobby
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 1000
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: f847f9e5-9494-4c4c-8f8e-4a4a4a4a4a4a
player_limit: -1
ip_forward: true
groups:
  MiniPentaax:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: false
forge_support: false
servers:
  lobby:
    motd: '&bLobby Principal'
    address: localhost:25565
    restricted: false
